export const FROM_AIRPORTS_LIST_REQUEST = "FROM_AIRPORTS_LIST_REQUEST";
export const FROM_AIRPORTS_LIST_SUCCESS = "FROM_AIRPORTS_LIST_SUCCESS";
export const FROM_AIRPORTS_LIST_FAILURE = "FROM_AIRPORTS_LIST_FAILURE";

export const TO_AIRPORTS_LIST_REQUEST = "TO_AIRPORTS_LIST_REQUEST";
export const TO_AIRPORTS_LIST_SUCCESS = "TO_AIRPORTS_LIST_SUCCESS";
export const TO_AIRPORTS_LIST_FAILURE = "TO_AIRPORTS_LIST_FAILURE";

export const FLIGHT_LIST_REQUEST = "FLIGHT_LIST_REQUEST";
export const FLIGHT_LIST_SUCCESS = "FLIGHT_LIST_SUCCESS";
export const FLIGHT_LIST_FAILURE = "FLIGHT_LIST_FAILURE";
